//! 桌面 Linux C 薄桥：`asgard_patch_native` → 平台 `asgard_linux_patch`。

/// 生成 `asgard_desktop_linux_bridge.c`。
pub fn generate_desktop_linux_bridge() -> String {
    r#"/* Generated by asgard — desktop Linux UiHost bridge. */
#include <string.h>

extern void asgard_linux_patch(const char *key, const char *value);

void asgard_patch_native(const char *key, const char *value) {
    asgard_linux_patch(key ? key : "", value ? value : "");
}
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn linux_bridge_forwards_patch() {
        let src = generate_desktop_linux_bridge();
        assert!(src.contains("asgard_patch_native"));
        assert!(src.contains("asgard_linux_patch"));
    }
}
