//! iOS 薄桥：`asgard_patch_native` → Swift `patchFromNative`（`asgard_invoke_export` 由 AOT dylib 提供）。

/// 生成 `asgard_ios_bridge.c`：与 Android ASGARDNT JNI 内嵌对称的 patch 回调。
pub fn generate_ios_bridge() -> String {
    r#"/* Generated by asgard — link with AOT logic or load via dlopen. */
#include <string.h>

extern void asgard_patch_native(const char *key, const char *value);

void asgard_patch_native(const char *key, const char *value) {
    asgard_patch_native_swift(key ? key : "", value ? value : "");
}

void asgard_patch_native_swift(const char *key, const char *value);
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ios_bridge_declares_patch_callback() {
        let src = generate_ios_bridge();
        assert!(src.contains("asgard_patch_native"));
        assert!(src.contains("asgard_patch_native_swift"));
    }
}
