//! 微信小游戏工程组装。

use std::{
    fs,
    path::{Path, PathBuf},
};

use miette::{IntoDiagnostic, Result, WrapErr};

use crate::delivery::PackReport;

/// 将 legion build 产物打包为微信小游戏工程。
pub fn pack_mini_game(input: &Path, output: Option<&Path>, wasm_name: Option<&str>) -> Result<PackReport> {
    let out = output.map(PathBuf::from).unwrap_or_else(|| input.join("wechat-game"));
    fs::create_dir_all(&out).into_diagnostic().wrap_err("create output dir")?;
    let wasm_path = find_wasm(input, wasm_name)?;
    let wasm_file_name = wasm_path.file_name().unwrap().to_string_lossy().into_owned();
    let dest_wasm = out.join(&wasm_file_name);
    if wasm_path != dest_wasm {
        fs::copy(&wasm_path, &dest_wasm).into_diagnostic().wrap_err("copy wasm")?;
    }

    let game_js = format!(
        r#"// Generated by asgard pack --target mini-game
const wasmPath = './{wasm_file_name}';

console.log('asgard mini-game boot');
if (typeof WXWebAssembly !== 'undefined') {{
  WXWebAssembly.instantiate(wasmPath).then(function (result) {{
    const exports = result.instance.exports;
    if (typeof exports.main === 'function') {{
      exports.main();
    }}
  }}).catch(function (err) {{
    console.error('wasm load failed', err);
  }});
}} else {{
  console.warn('WXWebAssembly unavailable; place runtime glue here');
}}
"#
    );
    fs::write(out.join("game.js"), game_js).into_diagnostic()?;
    fs::write(out.join("game.json"), "{\n  \"deviceOrientation\": \"portrait\"\n}\n").into_diagnostic()?;
    fs::write(
        out.join("project.config.json"),
        r#"{
  "description": "Asgard WeChat mini-game",
  "packOptions": { "ignore": [] },
  "setting": {
    "es6": true,
    "minified": false
  },
  "compileType": "game",
  "appid": "touristappid",
  "projectname": "asgard-mini-game"
}
"#,
    )
    .into_diagnostic()?;

    if let Some(parent) = wasm_path.parent() {
        if let Ok(entries) = fs::read_dir(parent) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) == Some("mjs") {
                    let name = path.file_name().unwrap();
                    fs::copy(&path, out.join(name)).into_diagnostic()?;
                }
            }
        }
    }
    Ok(PackReport { artifact_path: out.clone(), message: format!("mini-game project {}", out.display()) })
}

fn find_wasm(input: &Path, preferred: Option<&str>) -> Result<PathBuf> {
    if let Some(name) = preferred {
        let direct = input.join(name);
        if direct.exists() {
            return Ok(direct);
        }
        let nested = input.join("dist").join(name);
        if nested.exists() {
            return Ok(nested);
        }
    }
    let candidates = [input.to_path_buf(), input.join("dist"), input.join("dist").join("wasm32_unknown_browser_wasm")];
    for dir in candidates {
        if !dir.is_dir() {
            continue;
        }
        if let Ok(entries) = fs::read_dir(&dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) == Some("wasm") {
                    return Ok(path);
                }
            }
        }
    }
    Err(miette::miette!("未找到 .wasm；请先 `legion build` 或用 --wasm 指定"))
}
