//! 桌面 Windows C 薄桥：导出 `asgard_invoke_export` / `asgard_patch_native`（P/Invoke 用）。

/// 生成 `asgard_win_bridge.c`。
pub fn generate_desktop_win_bridge() -> String {
    r#"/* Generated by asgard — desktop Windows UiHost bridge. */
#ifdef _WIN32
#define ASGARD_EXPORT __declspec(dllexport)
#else
#define ASGARD_EXPORT
#endif

extern void asgard_invoke_export(const char *name);

ASGARD_EXPORT void asgard_invoke_export_forwarder(const char *name) {
    asgard_invoke_export(name ? name : "");
}

void asgard_patch_native_win(const char *key, const char *value);

ASGARD_EXPORT void asgard_patch_native(const char *key, const char *value) {
    asgard_patch_native_win(key ? key : "", value ? value : "");
}
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn win_bridge_exports_symbols() {
        let src = generate_desktop_win_bridge();
        assert!(src.contains("asgard_invoke_export"));
        assert!(src.contains("asgard_patch_native"));
    }
}
