//! AWSL 报告渲染集成测试（图表走 asgard glue，无手写业务 JS）。

use legion::cmds::report::{
    BenchReport, BenchResultRow, CoverageFeatureEntry, CoverageReport, TestResultEntry, build_standalone_html, render_bench_report,
    render_coverage_report, render_test_report,
};

/// HTML may only load scripts via `src=`; inline script bodies are forbidden JS patches.
fn assert_no_inline_scripts(html: &str) {
    let mut rest = html;
    while let Some(idx) = rest.find("<script") {
        let after = &rest[idx + 7..];
        let end = after.find('>').unwrap_or(after.len());
        let attrs = &after[..end];
        assert!(attrs.contains("src="), "inline <script> without src is forbidden (got: {attrs})");
        rest = &after[end.saturating_add(1)..];
    }
}

#[test]
fn test_report_html_structure() {
    let dir = tempfile::tempdir().unwrap();
    let results = vec![
        TestResultEntry { name: "add".into(), status: "pass".into(), error: None, target: "nyar".into() },
        TestResultEntry { name: "sub".into(), status: "compile_error".into(), error: Some("compile failed".into()), target: "clr".into() },
    ];
    render_test_report(dir.path(), "fixture", &results).unwrap();
    let html = std::fs::read_to_string(dir.path().join("index.html")).unwrap();
    assert!(html.contains("<!DOCTYPE html>"));
    assert!(html.contains("fixture - Test Report"));
    assert!(html.contains("status-badge pass"));
    assert!(html.contains("status-badge compile_error"));
    assert!(html.contains("compile failed"));
    assert!(html.contains("Generated by Legion CLI"));
    assert!(html.contains("data-island=\"hydrated\""));
    assert!(html.contains("data-component=\"chart-status\""));
    assert!(html.contains(r#"src="boot.js""#));
    assert_no_inline_scripts(&html);
    assert!(!html.contains("globalThis.__voa"));
    assert!(!html.contains("__voa.start"));
    assert!(dir.path().join("boot.js").exists());
    assert!(dir.path().join("c/chart-status.js").exists());
    assert!(dir.path().join("manifest.json").exists());
    let glue = std::fs::read_to_string(dir.path().join("c/chart-status.js")).unwrap();
    assert!(glue.contains("__voa.registerComponent"));
    assert!(glue.contains("callExport"), "glue must invoke WASM export, not inject HTML");
    assert!(!glue.contains("innerHTML"), "must not use innerHTML stub");
    let boot = std::fs::read_to_string(dir.path().join("boot.js")).unwrap();
    assert!(boot.contains("domAddEventExport"));
    assert!(boot.contains("rxBindLoop"));
    assert!(boot.contains("start('manifest.json')"), "boot.js must auto-start manifest");
    let manifest = std::fs::read_to_string(dir.path().join("manifest.json")).unwrap();
    assert!(manifest.contains("chart-status"));
    assert!(manifest.contains("c/chart-status.js"));
    assert!(!manifest.contains("/c/chart-status.js"), "report manifest uses relative URLs");
    assert!(!html.contains("plotter-interactive"));
    assert!(!html.contains("asgard-runtime.js"));
    assert!(!html.contains("LEGION_REPORT_SLOT"));
    assert!(!html.contains("LEGION_CHART_STATUS"));
}

#[test]
fn coverage_report_html_structure() {
    let dir = tempfile::tempdir().unwrap();
    let report = CoverageReport {
        covered: 2,
        total: 4,
        percentage: 50.0,
        features: vec![
            CoverageFeatureEntry { feature: "micro".into(), display: "micro 函数".into(), covered: true, projects: vec!["app".into()] },
            CoverageFeatureEntry { feature: "match".into(), display: "模式匹配".into(), covered: false, projects: vec![] },
        ],
    };
    render_coverage_report(dir.path(), &report).unwrap();
    let html = std::fs::read_to_string(dir.path().join("index.html")).unwrap();
    assert!(html.contains("Coverage Report"));
    assert!(html.contains("progress-fill"));
    assert!(html.contains("micro 函数"));
    assert!(html.contains("模式匹配"));
    assert!(html.contains("width: 50%"));
    assert!(html.contains("data-component=\"chart-coverage-balance\""));
    assert!(html.contains("data-component=\"chart-coverage-features\""));
    assert!(html.contains(r#"src="boot.js""#));
    assert_no_inline_scripts(&html);
    assert!(!html.contains("plotter-interactive"));
    assert!(!html.contains("LEGION_CHART_COVERAGE_BALANCE"));
}

#[test]
fn bench_report_html_structure() {
    let dir = tempfile::tempdir().unwrap();
    let report = BenchReport {
        runs: 3,
        rows: vec![
            BenchResultRow { project: "app".into(), test: "fib".into(), target: "nyar".into(), compile_ms: 10.0, runtime_ms: 2.5 },
            BenchResultRow { project: "lib".into(), test: "sort".into(), target: "clr".into(), compile_ms: 20.0, runtime_ms: 5.0 },
        ],
    };
    render_bench_report(dir.path(), &report).unwrap();
    let html = std::fs::read_to_string(dir.path().join("index.html")).unwrap();
    assert!(html.contains("Benchmark Report"));
    assert!(html.contains("2 项基准测试"));
    assert!(html.contains("fib"));
    assert!(html.contains("sort"));
    assert!(html.contains("10.0"));
    assert!(html.contains("data-component=\"chart-bench-runtime\""));
    assert!(html.contains("data-component=\"chart-bench-compile\""));
    assert!(html.contains(r#"src="boot.js""#));
    assert_no_inline_scripts(&html);
    assert!(!html.contains("plotter-interactive"));
    assert!(!html.contains("LEGION_CHART_BENCH_RUNTIME"));
}

#[test]
fn test_report_standalone_html_is_self_contained() {
    let dir = tempfile::tempdir().unwrap();
    let results = vec![
        TestResultEntry { name: "add".into(), status: "pass".into(), error: None, target: "nyar".into() },
        TestResultEntry { name: "sub".into(), status: "fail".into(), error: Some("boom".into()), target: "nyar".into() },
    ];
    render_test_report(dir.path(), "fixture", &results).unwrap();
    build_standalone_html(dir.path(), "standalone.html").unwrap();

    let html = std::fs::read_to_string(dir.path().join("standalone.html")).unwrap();
    assert!(html.contains("<!DOCTYPE html>"));
    assert!(html.contains("fixture - Test Report"));
    assert!(html.contains("data-component=\"chart-status\""));
    assert!(!html.contains(r#"src="boot.js""#));
    assert!(!html.contains(r#"href="legion-test.css""#));
    assert!(html.contains("__voaStandaloneWasmBytes"));
    assert!(html.contains("globalThis.fetch"));
    assert!(html.contains("start('manifest.json')"));
    assert!(html.contains("asgard-icol") || html.contains("asgard-icol-bar") || html.contains(".chart-panel"));
}

#[test]
fn coverage_report_standalone_html_is_self_contained() {
    let dir = tempfile::tempdir().unwrap();
    let report = CoverageReport {
        covered: 2,
        total: 4,
        percentage: 50.0,
        features: vec![
            CoverageFeatureEntry { feature: "micro".into(), display: "micro 函数".into(), covered: true, projects: vec!["app".into()] },
            CoverageFeatureEntry { feature: "match".into(), display: "模式匹配".into(), covered: false, projects: vec![] },
        ],
    };
    render_coverage_report(dir.path(), &report).unwrap();
    build_standalone_html(dir.path(), "standalone.html").unwrap();
    let html = std::fs::read_to_string(dir.path().join("standalone.html")).unwrap();
    assert!(!html.contains(r#"src="boot.js""#));
    assert!(html.contains("__voaStandaloneWasmBytes"));
}

#[test]
fn bench_report_standalone_html_is_self_contained() {
    let dir = tempfile::tempdir().unwrap();
    let report = BenchReport {
        runs: 3,
        rows: vec![BenchResultRow { project: "app".into(), test: "fib".into(), target: "nyar".into(), compile_ms: 12.5, runtime_ms: 1.2 }],
    };
    render_bench_report(dir.path(), &report).unwrap();
    build_standalone_html(dir.path(), "standalone.html").unwrap();
    let html = std::fs::read_to_string(dir.path().join("standalone.html")).unwrap();
    assert!(!html.contains(r#"src="boot.js""#));
    assert!(html.contains("__voaStandaloneWasmBytes"));
}
